repos:
  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bundle exec rubocop --autocorrect
        language: system
        pass_filenames: false

      - id: rails-test
        name: Rails Test
        entry: bin/rails test
        language: system
        pass_filenames: false
